### ISSUE TITLE
Android build problem with 1.9.1

### ISSUE THREAD

**Issue by KMIxx** [cleverpush/cleverpush-flutter-sdk#20]
Hello

After upgrading to 1.9.0 or 1.9.1 our CI build is failing with the following error:
```
/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:172: error: local variable reply is accessed from within inner class; needs to be declared final

          replySuccess(reply, CleverPushSerializer.convertChannelTopicToMapList(new ArrayList<ChannelTopic>(channelTopics)));
```

There are also multiple warning but these will not fail the build so these do not have much priority in this stage:
```

/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:27: warning: [deprecation] Registrar in PluginRegistry has been deprecated

import io.flutter.plugin.common.PluginRegistry.Registrar;

                                              ^

/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:28: warning: [deprecation] FlutterNativeView in io.flutter.view has been deprecated

import io.flutter.view.FlutterNativeView;

                      ^

/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/FlutterRegistrarResponder.java:12: warning: [deprecation] Registrar in PluginRegistry has been deprecated

   PluginRegistry.Registrar flutterRegistrar;

                 ^

/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:34: warning: [deprecation] Registrar in PluginRegistry has been deprecated

  public static void registerWith(Registrar registrar) {

                                  ^

/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:41: warning: [deprecation] ViewDestroyListener in PluginRegistry has been deprecated

    plugin.flutterRegistrar.addViewDestroyListener(new PluginRegistry.ViewDestroyListener() {

                                                                     ^

/Users/builder/programs/flutter_2_2_3/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:43: warning: [deprecation] FlutterNativeView in io.flutter.view has been deprecated

      public boolean onViewDestroy(FlutterNativeView flutterNativeView) {
```

Could you take a look as it seems to be coming from the SDK side?

**Comment by gbhrdt** [comment]
Hi @KMIxx unfortunately we can not replicate it on our side.
Could you please share your app-level and project build.gradle files? Thank you!

**Comment by KMIxx** [comment]
Sure, app level build.gradle:

**Comment by KMIxx** [comment]
I found a way to reproduce a problem.

Steps:
1. Create a totally new project (i created it with Android Studio Flutter project creation wizard aka from the menu: File -> New -> New Flutter project)
2. Add Cleverpush dependency: "cleverpush_flutter: 1.9.1" to pubspec.yaml
3. Update app level build.gradle file, upgrade "minSdkVersion" to 19
4. Rung "flutter build apk --debug -t lib/main.dart" on the project root directory

It yields error:
```
/Users/kmi/Development/flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/cleverpush_flutter-1.9.1/android/src/main/java/com/cleverpush/flutter/CleverPushPlugin.java:172: error: local variable reply is accessed from within inner class; needs to be declared final
          replySuccess(reply, CleverPushSerializer.convertChannelTopicToMapList(new ArrayList<ChannelTopic>(channelTopics)));
```

**Comment by gbhrdt** [comment]
Thanks @KMIxx !
We've just released 1.9.2 which should fix it.
